apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.port.frontend }}
      targetPort: {{ .Values.port.frontend }}
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{ - else }}
  type: NodePort
  {{ - end }}
