apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - name: mongo
      port: {{ .Values.port.mongo }}
      targetPort: {{ .Values.port.mongo }}
  type: {{ .Values.service.mongo.type }}
